In [1]:
import numpy as np
import torch as t
from matplotlib import pyplot as plt

In [6]:
s = t.rand(2,2)
s

tensor([[0.4032, 0.0995],
        [0.9925, 0.6339]])

In [11]:
s.view(1,4)

tensor([[0.4032, 0.0995, 0.9925, 0.6339]])

In [12]:
s.view(4,1)

tensor([[0.4032],
        [0.0995],
        [0.9925],
        [0.6339]])

In [46]:
t.rand(4,3,2).reshape(6,4)

tensor([[0.0356, 0.5985, 0.4540, 0.9145],
        [0.0778, 0.2131, 0.3330, 0.5365],
        [0.3576, 0.1621, 0.4083, 0.1403],
        [0.7701, 0.5402, 0.0233, 0.7206],
        [0.1324, 0.3397, 0.7052, 0.6969],
        [0.3621, 0.6598, 0.1375, 0.5587]])

In [55]:
sd = t.rand(4,3,2)
sd.stride()

(6, 2, 1)

In [51]:
sd.reshape(3,2,2,2)

tensor([[[[0.8823, 0.6380],
          [0.1402, 0.4532]],

         [[0.9708, 0.8675],
          [0.7901, 0.0142]]],


        [[[0.5817, 0.1336],
          [0.5186, 0.8799]],

         [[0.0984, 0.3387],
          [0.2320, 0.0304]]],


        [[[0.0882, 0.5168],
          [0.1778, 0.3615]],

         [[0.7555, 0.3755],
          [0.4596, 0.3820]]]])

In [54]:
sd.view(3,2,2,2).stride()

(8, 4, 2, 1)

In [57]:
t.rand(1,4).view(4,1)

tensor([[0.6518],
        [0.0187],
        [0.1419],
        [0.4129]])